yarnPath: .yarn/releases/yarn-3.2.0.cjs
nodeLinker: node-modules
# packageExtensions:
#   "@electron-forge/cli@*":
#     dependencies:
#       "source-map-support": "^0.5.13"
#   "@electron-forge/async-ora@*":
#     dependencies:
#       "source-map-support": "^0.5.13"
#   "@electron-forge/shared-types@*":
#     dependencies:
#       "source-map-support": "^0.5.13"
#   "@electron-forge/template-base@*":
#     dependencies:
#       "source-map-support": "^0.5.13"
#   "@electron-forge/plugin-base@*":
#     dependencies:
#       "source-map-support": "^0.5.13"
#   "@electron-forge/installer-base@*":
#     dependencies:
#       "source-map-support": "^0.5.13"
#   "@electron-forge/installer-dmg@*":
#     dependencies:
#       "source-map-support": "^0.5.13"
#   "@electron-forge/installer-darwin@*":
#     dependencies:
#       "source-map-support": "^0.5.13"
#   "@electron-forge/installer-zip@*":
#     dependencies:
#       "source-map-support": "^0.5.13"
#   "@electron-forge/installer-deb@*":
#     dependencies:
#       "source-map-support": "^0.5.13"
#   "@electron-forge/installer-linux@*":
#     dependencies:
#       "source-map-support": "^0.5.13"
#   "@electron-forge/installer-rpm@*":
#     dependencies:
#       "source-map-support": "^0.5.13"
#   "@electron-forge/installer-exe@*":
#     dependencies:
#       "source-map-support": "^0.5.13"
#   "@electron-forge/maker-base@*":
#     dependencies:
#       "source-map-support": "^0.5.13"
